Repository mn-pollinators/pollinator-facts, pull requests merged in 2020-06, with the labels that each got.

#15 Update README and other docs
  README.md
Labels: documentation

#8 Create Fact “night-blooming”
  src/facts/night-blooming.md
  src/images/night-blooming_cereus-crop.jpg
Labels: netlify-cms/pending_publish

#7 Create Fact “buzz-pollination”
  src/facts/buzz-pollination.md
  src/images/10243478783_5f4bc02b57_o-crop.jpg
Labels: netlify-cms/pending_review

#59 Update Fact “milkweed”
  src/facts/milkweed.md
Labels: netlify-cms/pending_publish

#63 Create Fact “american-plum”
  src/facts/american-plum.md
  src/images/american-plum.jpg
Labels: netlify-cms/pending_review

#70 Create Fact “black-eyed-susan”
  src/facts/black-eyed-susan.md
  src/images/black-eyed-susan.jpg
Labels: netlify-cms/pending_review

#56 Create Fact “meadow-blazingstar”
  src/facts/meadow-blazingstar.md
  src/images/15120801615_9334187129_h.jpg
Labels: netlify-cms/pending_publish
